/** 地月转移：真实有限燃烧、目标安全距离、预测偏差与回放确定性。 */
import { Content, json } from 'Dora';
import { P2, bodyPositionAt, distance, simulate } from 'game/Gravity';
import { getLevel, goalPositionAt, installArcadeLevels, findGoalIndex, evaluateRocketsDetailed } from 'game/LevelData';
import { advanceTransferPlayback, analyzeFlyby, nextCameraFocus, planTransfer, successMarkerFrame, transferPlaybackRate, transferShotAt } from 'game/Transfer';
import { GameLevel, createCore, coreEndViewing, coreLaunch, coreUpdate, coreRetry, selectIdleHost } from 'game/Game';

export function runTests(): string {
	let checks = 0;
	const failures: string[] = [];
	const check = (name: string, ok: boolean): void => { checks += 1; if (!ok) failures.push(name); };
	installArcadeLevels(Content.load('Assets/Levels/levels.json'), Content.load('Assets/Levels/bodies.json'), (text: string): unknown => json.decode(text)[0]);
	const lv = getLevel(0);
	if (lv === undefined || lv.transfer === undefined || lv.transfer.flyby === undefined) return 'failed\nmissing transfer fixture';
	const tr = lv.transfer;
	const cfg = lv.transfer.flyby;
	const dt = 0.016;
	check('marker-idle-visible', successMarkerFrame(-1).visible && successMarkerFrame(-1).alpha === 1);
	check('marker-bright-pulse', successMarkerFrame(0.10).scale > 1.5 && successMarkerFrame(0.10).ring === 0);
	check('marker-expands-and-fades', successMarkerFrame(0.3).ring > 8 && successMarkerFrame(0.3).alpha < 1);
	check('marker-hidden-at-0.6', !successMarkerFrame(0.6).visible && successMarkerFrame(0.6).alpha === 0);
	check('marker-stays-hidden', !successMarkerFrame(10).visible);
	const radius = distance(lv.probeStart, bodyPositionAt(lv.planets[0], 0));
	const date = 1, power = 0.875;
	const startAt = (t: number): { pos: P2; vel: P2 } => {
		const a = Math.atan2(lv.probeStart.y, lv.probeStart.x) + Math.sqrt(lv.planets[0].gm / (radius * radius * radius)) * t;
		const speed = Math.sqrt(lv.planets[0].gm / radius);
		return { pos: { x: radius * Math.cos(a), y: radius * Math.sin(a) }, vel: { x: -Math.sin(a) * speed, y: Math.cos(a) * speed } };
	};
	const start = startAt(date);
	const plan = planTransfer(lv.planets[0].gm, radius, start.vel, power, tr.apoapsisMax);
	const level: GameLevel = { levelId: 1, viewingSeconds: 24, bonusPoints: lv.bonusPoints, bodies: lv.planets, probeStart: lv.probeStart, probeVel0: lv.probeVel0, goal: lv.goal, escapeRadius: lv.escapeRadius, maxSteps: lv.maxSteps, transfer: tr };
	const core = createCore(dt);
	core.t0 = date;
	core.aim.velocity = plan.velocity;
	coreLaunch(core, plan.velocity, level, start.pos, start.vel);
	core.playback = 1;
	check('earth-moon-only', lv.planets.length === 2 && lv.planets[1].name === '月球');
	check('low-orbit-height', Math.abs(radius - lv.planets[0].radius - 90) < 1e-9);
	check('nearest-earth-at-low-orbit', selectIdleHost(lv.planets, lv.probeStart) === 0);
	check('explicit-earth-host', selectIdleHost(lv.planets, lv.probeStart, 0) === 0);
	check('no-stars', lv.stars !== undefined && lv.stars.length === 0);
	check('completion-only', lv.mission !== undefined && lv.mission.challenges.length === 1);
	check('prograde-only', Math.abs(plan.velocity.x * start.vel.y - plan.velocity.y * start.vel.x) < 1e-9);
	check('zero-burn', planTransfer(lv.planets[0].gm, radius, lv.probeVel0, 0, tr.apoapsisMax).dv === 0);
	check('power-clamped', planTransfer(lv.planets[0].gm, radius, lv.probeVel0, 2, tr.apoapsisMax).apoapsis === tr.apoapsisMax);
	check('burn-about-0.3s', core.burnDuration > 0.25 && core.burnDuration < 0.35);
	check('planned-safe-flyby', core.flyby !== undefined && core.goalIndex >= 0 && core.flyby.energyDrop >= cfg.minEnergyDrop);
	check('completion-not-visible-at-launch', !core.missionCompleted);
	check('cannot-end-before-completion', !coreEndViewing(core));
	const actual = core.flight;
	if (actual === undefined) return 'failed\nmissing flight';
	check('no-instant-impulse', distance(actual.velocities[0], start.vel) < 1e-10);
	const ref = simulate({ pos: start.pos, vel: { x: start.vel.x + plan.velocity.x, y: start.vel.y + plan.velocity.y } }, lv.planets, { dt, steps: lv.maxSteps, sampleEvery: 1, escapeRadius: lv.escapeRadius, t0: date });
	const reference = analyzeFlyby(ref, lv.planets[0], lv.planets[1], cfg, dt, date);
	check('reference-safe-flyby', reference.completionIndex >= 0);
	const peri = core.flyby !== undefined ? core.flyby.periapsisIndex : 0;
	const drift = distance(actual.points[peri], ref.points[peri]);
	check('small-nonzero-drift', drift > 0.01 && drift < 20);
	check('periapsis-drift-tolerated', core.flyby !== undefined && Math.abs(core.flyby.periapsis - reference.periapsis) < 5);
	const accelerated = analyzeFlyby(actual, lv.planets[0], lv.planets[1], { ...cfg, minEnergyDrop: 1000 }, dt, date);
	check('energy-drop-is-required', accelerated.completionIndex < 0);
	check('close-pass-is-required', analyzeFlyby(actual, lv.planets[0], lv.planets[1], { ...cfg, maxPeriapsis: 45 }, dt, date).completionIndex < 0);
	check('safety-margin-is-required', analyzeFlyby(actual, lv.planets[0], lv.planets[1], { ...cfg, minPeriapsis: 60 }, dt, date).completionIndex < 0);
	const timeout = analyzeFlyby(actual, lv.planets[0], lv.planets[1], { ...cfg, returnRadius: 1 }, dt, date);
	check('view-timeout-without-earth-return', timeout.completionIndex >= 0 && timeout.viewEndIndex === timeout.completionIndex + Math.floor(cfg.maxViewingTime / dt));
	const light = createCore(dt);
	light.t0 = date;
	coreLaunch(light, plan.velocity, level, start.pos, start.vel);
	const lightIndex = core.goalIndex - 1;
	light.flightTime = lightIndex * dt;
	light.playback = 0;
	coreUpdate(light, 0, level);
	check('light-does-not-complete', lightIndex >= 0 && lightIndex < core.goalIndex && light.phase === 'Flying' && !light.missionCompleted);
	light.flightTime = core.goalIndex * dt;
	coreUpdate(light, 0, level);
	check('flyby-completes-without-ending', light.missionCompleted && light.phase === 'Flying' && light.result === 'success');
	check('manual-end-after-completion', coreEndViewing(light) && light.phase === 'Result' && light.result === 'success');
	for (let t = 0; t < 80; t += 20) {
		const moon = bodyPositionAt(lv.planets[1], t);
		const goal = goalPositionAt(lv.planets[1], t, lv.goal.offset);
		check('safe-goal-' + t.toFixed(0), distance(moon, goal) > lv.planets[1].radius + lv.goal.tolerance);
	}
	const opts = { dt, steps: 100, sampleEvery: 1, escapeRadius: 0, initialBurn: { acceleration: { x: 10, y: 0 }, duration: 0.301 } };
	const fractional = simulate({ pos: { x: 0, y: 0 }, vel: { x: 0, y: 0 } }, [], opts);
	check('fractional-last-burn-step', Math.abs(fractional.state.vel.x - 3.01) < 1e-10);
	const twice = simulate({ pos: { x: 0, y: 0 }, vel: { x: 0, y: 0 } }, [], opts);
	check('burn-deterministic', fractional.state.pos.x === twice.state.pos.x && fractional.state.vel.x === twice.state.vel.x);
	const pausedAt = core.flightTime;
	core.playback = 0;
	for (let i = 0; i < 50; i++) coreUpdate(core, 1 / 60, level);
	check('pause-freezes-burn', core.flightTime === pausedAt);
	core.playback = 1;
	let wall = 0;
	while (core.phase === 'Flying' && wall < 40) { coreUpdate(core, 1 / 60, level); wall += 1 / 60; }
	check('12-to-18s-playback', wall >= 12 && wall <= 18);
	check('return-clamped', core.phase === 'Result' && core.missionCompleted && core.flyby !== undefined && core.flightTime === core.flyby.viewEndIndex * dt && core.flightTime > core.goalIndex * dt);
	check('return-near-earth', distance(actual.points[Math.floor(core.flightTime / dt)], bodyPositionAt(lv.planets[0], date + core.flightTime)) <= cfg.returnRadius);
	const fast = createCore(dt);
	fast.t0 = date;
	coreLaunch(fast, plan.velocity, level, start.pos, start.vel);
	fast.playback = 4;
	for (let i = 0; i < 1000 && fast.phase === 'Flying'; i++) coreUpdate(fast, 1 / 120, level);
	check('speed-does-not-change-result', fast.result === core.result && fast.flightTime === core.flightTime && fast.flight !== undefined && distance(fast.flight.points[fast.goalIndex], actual.points[core.goalIndex]) === 0);
	const low = createCore(dt);
	low.t0 = date;
	coreLaunch(low, planTransfer(lv.planets[0].gm, radius, start.vel, 0.05, tr.apoapsisMax).velocity, level, start.pos, start.vel);
	check('low-power-misses', low.goalIndex < 0);
	const wrong = createCore(dt);
	wrong.t0 = 1.8;
	const wrongStart = startAt(wrong.t0);
	coreLaunch(wrong, planTransfer(lv.planets[0].gm, radius, wrongStart.vel, power, tr.apoapsisMax).velocity, level, wrongStart.pos, wrongStart.vel);
	check('wrong-phase-flyby-misses', wrong.flyby !== undefined && wrong.flyby.completionIndex < 0);
	const collision = simulate({ pos: bodyPositionAt(lv.planets[1], 0), vel: { x: 0, y: 0 } }, lv.planets, { dt, steps: 10, sampleEvery: 1, escapeRadius: 0 });
	check('moon-is-solid', collision.outcome === 'crashed');
	check('moon-is-not-target', findGoalIndex(collision.points, lv.planets, lv.goal, dt, 0) < 0);
	check('collision-cannot-complete', analyzeFlyby(collision, lv.planets[0], lv.planets[1], cfg, dt, 0).completionIndex < 0);
	const collideCore = createCore(dt);
	coreLaunch(collideCore, { x: 0, y: 0 }, level, bodyPositionAt(lv.planets[1], 0), { x: 0, y: 0 });
	coreUpdate(collideCore, 1, level);
	check('collision-fails-before-completion', collideCore.phase === 'Result' && collideCore.result === 'crashed' && !collideCore.missionCompleted);
	const afterCrash = createCore(dt);
	coreLaunch(afterCrash, { x: 0, y: 0 }, level, bodyPositionAt(lv.planets[1], 0), { x: 0, y: 0 });
	// 模拟已播放完安全掠月之后的自然撞毁/逃逸；完成状态只能单向锁定。
	afterCrash.missionCompleted = true; afterCrash.result = 'success';
	coreUpdate(afterCrash, 1, level);
	check('completion-survives-later-collision', afterCrash.phase === 'Result' && afterCrash.result === 'success');
	check('launch-shot', transferShotAt(0, core.burnDuration, core.flyby, cfg, dt) === 'Launch');
	check('cruise-shot', transferShotAt(4, core.burnDuration, core.flyby, cfg, dt) === 'Cruise');
	check('moon-shot', transferShotAt(peri * dt, core.burnDuration, core.flyby, cfg, dt) === 'Moon');
	check('overview-shot', transferShotAt(core.flyby!.completionIndex * dt + 1, core.burnDuration, core.flyby, cfg, dt) === 'Overview');
	check('return-shot', transferShotAt(core.flyby!.completionIndex * dt + cfg.overviewDuration + 0.1, core.burnDuration, core.flyby, cfg, dt) === 'Earth');
	check('camera-cycle', nextCameraFocus(nextCameraFocus(nextCameraFocus(nextCameraFocus(nextCameraFocus('Auto'))))) === 'Auto');
	check('burn-at-1x', transferPlaybackRate(0.1, core.burnDuration, tr, core.flyby, dt) === 1);
	check('coast-at-3x', transferPlaybackRate(4, core.burnDuration, tr, core.flyby, dt) === 3);
	check('periapsis-at-1x', transferPlaybackRate(peri * dt, core.burnDuration, tr, core.flyby, dt) === 1);
	let at30 = 0, at120 = 0;
	for (let i = 0; i < 360; i++) at30 = advanceTransferPlayback(at30, 1 / 30, 1, core.burnDuration, tr, core.flyby, dt);
	for (let i = 0; i < 1440; i++) at120 = advanceTransferPlayback(at120, 1 / 120, 1, core.burnDuration, tr, core.flyby, dt);
	check('frame-rate-independent-playback', Math.abs(at30 - at120) < 1e-9);
	const score = evaluateRocketsDetailed(lv, 'success', plan.dv, { starsCollected: 3 });
	check('no-phantom-stars', score.rockets === 1 && !score.achieved[1] && !score.achieved[2]);
	coreRetry(core, 0);
	check('retry-aiming', core.phase === 'Aiming' && core.flight === undefined && !core.missionCompleted && core.flyby === undefined);
	check('l2-configured', getLevel(1) !== undefined && getLevel(1)!.transfer!.orbital !== undefined && getLevel(1)!.stars!.length === 0);
	check('l3-configured', getLevel(2) !== undefined && getLevel(2)!.transfer!.orbital !== undefined && getLevel(2)!.stars!.length === 0);
	return (failures.length === 0 ? 'passed' : 'failed') + '\nchecks=' + checks.toFixed(0) + ' failures=' + failures.length.toFixed(0) + (failures.length > 0 ? '\n' + failures.join('\n') : '');
}
